ktor:
  development: true
  deployment:
    port: 8080
    watch:
      - classes
  application:
    modules:
      - com.oyera.ApplicationKt.module
postgres:
  url: "jdbc:postgresql://ep-holy-recipe-a4kkzgeg.us-east-1.aws.neon.tech/CloseLibrary_DEV?sslmode=require"
  driverClass: "org.postgresql.Driver"
  user: neondb_owner
  password: DGCn3V6rBlWo